<?php

class GlobalLink {

  public $documentTicket; //String
  public $submissionTicket; //String
  public $submissionName; //String
  public $sourceLocale; //String
  public $targetLocale; //String array
  public $sourceXML; //String
  public $targetTicket; //String
  public $targetXML; //String
  public $status; //String
  public $tptRowId; //String
  public $nid; //String
  public $vid; //String
  public $title; //String
  public $type; //String
  public $sourceFileName; //String
  public $dueDate; //long
  public $cancelled = FALSE; //boolean
  public $sourceDeleted = FALSE; //boolean
  public $otherObjectId;//String
  public $errorMessage;
  public $submissionInstructions; //String
  public $submitter; //String
  public $metadata; //String

}