<?php

/**
 * @file
 * Transperfect menu translation module.
 *
 * This module adds menu translation support with configuration options.
 */

/**
 * Implements hook_menu().
 */
function transperfect_menu_menu() {
  $items = array();

  $items ['admin/transperfect-translations/dashboard/menu'] = array(
    'title' => ' Menus ',
    'page callback' => 'transperfect_menu_dashboard',
    'access callback' => 'transperfect_access_callback_any',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'transperfect_menu_send.inc',
    'page arguments' => array('menu'),
  );

  $items ['admin/transperfect-translations/activeSubmissions/menu'] = array(
    'title' => ' Menus ',
    'page callback' => 'transperfect_menu_active_submissions',
    'access callback' => 'transperfect_access_callback_any',
    'file' => 'transperfect_menu_active_submissions.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'page arguments' => array('menu'),
  );

  $items ['admin/transperfect-translations/receiveTranslation/menu'] = array(
    'title' => ' Menus ',
    'page callback' => 'transperfect_menu_receive_submissions',
    'access callback' => 'transperfect_access_callback_any',
    'file' => 'transperfect_menu_receive.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'page arguments' => array('menu'),
  );

  $items['admin/transperfect-translations/receiveTranslation/menu/preview'] = array(
    'title' => 'Preview Translation',
    'page callback' => 'transperfect_menu_preview_translated_content',
    'file' => 'transperfect_menu_receive.inc',
    'access arguments' => array(TPT_ROLE_MANAGE_TRANSLATIONS),
    'type' => MENU_CALLBACK,
  );

  return $items;
}
