<?php

/**
 * Implements hook_menu().
 */
function transperfect_webform_menu() {
  $items = array();

  $items [transperfect_get_root_menu('transperfect-translations/dashboard/webform')] = array(
      'title' => ' Webforms ',
      'page callback' => 'transperfect_dashboard_webform_page',
      'access callback' => 'tpt_access_callback_any',
      'type' => MENU_LOCAL_TASK,
      'file' => 'transperfect_webform_send.inc',
      'weight' => 10,
      'page arguments' => array('webform'),
  );

  $items [transperfect_get_root_menu('transperfect-translations/activeSubmissions/webform')] = array(
      'title' => ' Webforms ',
      'page callback' => 'transperfect_webform_active_submissions',
      'access callback' => 'tpt_access_callback_any',
      'file' => 'transperfect_webform_active_submissions.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
      'page arguments' => array('webform'),
  );

  $items [transperfect_get_root_menu('transperfect-translations/receiveTranslation/webform')] = array(
      'title' => ' Webforms ',
      'page callback' => 'transperfect_webform_receive_submissions',
      'access callback' => 'tpt_access_callback_any',
      'file' => 'transperfect_webform_receive.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
      'page arguments' => array('webform'),
  );

  $items[transperfect_get_root_menu('transperfect-translations/receiveTranslation/webform/preview')] = array(
      'title' => 'Preview Translation',
      'page callback' => 'preview_translated_webform_content',
      'file' => 'transperfect_webform_receive.inc',
      'access callback' => 'tpt_access_callback_admin',
      'type' => MENU_CALLBACK,
  );

  return $items;
}
