<?php

/**
 * Implements hook_menu().
 */
function transperfect_taxonomy_menu() {
  $items = array();

  $items [transperfect_get_root_menu('transperfect-translations/dashboard/taxonomy')] = array(
      'title' => ' Taxonomy ',
      'page callback' => 'transperfect_dashboard_taxonomy',
      'access callback' => 'tpt_access_callback_any',
      'type' => MENU_LOCAL_TASK,
      'file' => 'transperfect_taxonomy_send.inc',
      'weight' => 10,
      'page arguments' => array('taxonomy'),
  );

  $items [transperfect_get_root_menu('transperfect-translations/activeSubmissions/taxonomy')] = array(
      'title' => ' Taxonomy ',
      'page callback' => 'transperfect_taxonomy_active_submissions',
      'access callback' => 'tpt_access_callback_any',
      'file' => 'transperfect_taxonomy_active_submissions.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
      'page arguments' => array('taxonomy'),
  );

  $items [transperfect_get_root_menu('transperfect-translations/receiveTranslation/taxonomy')] = array(
      'title' => ' Taxonomy ',
      'page callback' => 'transperfect_taxonomy_receive_submissions',
      'access callback' => 'tpt_access_callback_any',
      'file' => 'transperfect_taxonomy_receive.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
      'page arguments' => array('taxonomy'),
  );

  $items[transperfect_get_root_menu('transperfect-translations/receiveTranslation/taxonomy/preview')] = array(
      'title' => 'Preview Translation',
      'page callback' => 'preview_translated_taxonomy_content',
      'file' => 'transperfect_taxonomy_receive.inc',
      'access callback' => 'tpt_access_callback_admin',
      'type' => MENU_CALLBACK,
  );

  return $items;
}
