<?php

/**
 * Implements hook_menu().
 */
function transperfect_menu_menu() {
  $items = array();

  $items [transperfect_get_root_menu('transperfect-translations/dashboard/menu')] = array(
      'title' => ' Menus ',
      'page callback' => 'transperfect_dashboard_menu',
      'access callback' => 'tpt_access_callback_any',
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
      'file' => 'transperfect_menu_send.inc',
      'page arguments' => array('menu'),
  );

  $items [transperfect_get_root_menu('transperfect-translations/activeSubmissions/menu')] = array(
      'title' => ' Menus ',
      'page callback' => 'transperfect_menu_active_submissions',
      'access callback' => 'tpt_access_callback_any',
      'file' => 'transperfect_menu_active_submissions.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
      'page arguments' => array('menu'),
  );

  $items [transperfect_get_root_menu('transperfect-translations/receiveTranslation/menu')] = array(
      'title' => ' Menus ',
      'page callback' => 'transperfect_menu_receive_submissions',
      'access callback' => 'tpt_access_callback_any',
      'file' => 'transperfect_menu_receive.inc',
      'type' => MENU_LOCAL_TASK,
      'weight' => 10,
      'page arguments' => array('menu'),
  );

  $items[transperfect_get_root_menu('transperfect-translations/receiveTranslation/menu/preview')] = array(
      'title' => 'Preview Translation',
      'page callback' => 'preview_translated_menu_content',
      'file' => 'transperfect_menu_receive.inc',
      'access callback' => 'tpt_access_callback_admin',
      'type' => MENU_CALLBACK,
  );

  return $items;
}
